#!/bin/bash
# Run this setup to configure the anomaly-detective server

# # Setup local library to load R packages
# mkdir -p ~/R ~/R/library         # Only need do this once
# #echo 'R_LIBS_USER="~/R/library"' >  $HOME/.Renviron
# #source $HOME/.Renviron
# setenv R_LIBS_USER "~/R/library"
# Rscript scripts/setup.r

# # Start Rserve
# Rscript scripts/rserve.r > /dev/null &

# Setup the timeseries data
datadir=$1
metrics=$2

set -e
rm -f data/important.txt
rm -rf data/timeseries/*
rm -rf data/timeseries_json/*
mkdir -p data/timeseries_json
touch data/important.txt
while read p; do ls $datadir | grep "$p" >> data/important.txt; done < $metrics
python scripts/create_ts_list.py data/important.txt data/important.json
while read p; do cp -v $datadir/$p data/timeseries; done < data/important.txt
python scripts/ts_to_json.py $datadir data/important.txt data/timeseries_json
